create database blinkitdb;
use blinkitdb;


select * from blinkit;

select count(*) from blinkit;


ALTER TABLE blinkit
CHANGE COLUMN `ï»¿Item Fat Content` item_fat_content TEXT;



describe blinkit;

SET SQL_SAFE_UPDATES = 0;



-- Data cleaning
update blinkit
set item_fat_content=
case
when item_fat_content in('LF','low fat') then 'Low Fat'
when item_fat_content= 'reg' then 'Regular'
else item_fat_content
end;


SELECT distinct(item_fat_content) from blinkit;

-- Total sales
select sum(`Total Sales`) from blinkit;

select cast(sum(`Total Sales`)/1000000 as decimal(10,2)) as total_sales_millions from blinkit;



-- Avg sales

select round(avg(`Total Sales`),1) as average_sales from blinkit;


-- total items

select count(*) as total_items from blinkit;


-- total sales for low fat

select cast(sum(`Total Sales`)/1000000 as decimal(10,2)) as total_sales_millions from blinkit
where item_fat_content='Low Fat';


-- avg rating
select cast(avg(Rating)as decimal(10,2)) as average_rating from blinkit;


-- Business problem

-- query to find the total sales by different fat content
select item_fat_content ,cast(sum(`Total Sales`)/1000 as decimal(10,2)) as total_sales_thousand
from blinkit
group by item_fat_content
order by total_sales_thousand desc;


-- query to find the average sales by different fat content

select item_fat_content ,cast(avg(`Total Sales`)as decimal(10,1)) as avg_sales_by_fat_content
from blinkit
group by item_fat_content
order by avg_sales_by_fat_content  desc;


-- query to find the count of  sales by different fat content

select item_fat_content,count(*) as total_count
from blinkit
group by item_fat_content
order by total_count desc;


-- query to find the rating by different fat content

select item_fat_content,cast(avg(rating) as decimal(10,2)) as avg_rating
from blinkit
group by item_fat_content
order by avg_rating desc; 


-- query to find the sum,avg,count,and average rating by different item type


SELECT `Item Type`,
    CAST(SUM(`Total Sales`) AS DECIMAL(10,2)) AS Total_Sales,
    CAST(AVG(`Total Sales`) AS DECIMAL(10,1)) AS Avg_Sales,
    COUNT(*) AS `No Of Items`,
    CAST(AVG(Rating) AS DECIMAL(10,2)) AS Avg_Rating
FROM blinkit
GROUP BY `Item Type`
ORDER BY `Total_Sales` DESC
limit 5;



select * from blinkit;

-- query to find the total sales generated by each Outlet Location Type, broken down by Item Fat Content (Low Fat and Regular)?

SELECT 
    `Outlet Location Type`,
    ROUND(SUM(CASE 
        WHEN Item_Fat_Content = 'Low Fat' 
        THEN `Total Sales` 
        ELSE 0 
    END), 2) AS Low_Fat,
    
    ROUND(SUM(CASE 
        WHEN Item_Fat_Content = 'Regular' 
        THEN `Total Sales` 
        ELSE 0 
    END), 2) AS Regular

FROM blinkit

GROUP BY `Outlet Location Type`

ORDER BY `Outlet Location Type`;


-- query total sales generated for each Outlet Establishment Year


SELECT `Outlet Establishment Year`, CAST(SUM(`Total Sales`) AS DECIMAL(10,2)) AS Total_Sales
FROM blinkit
GROUP BY `Outlet Establishment Year`
ORDER BY `Outlet Establishment Year` ASC;


--  query to find total sales and sales percentage contributed by each Outlet Size

SELECT 
    `Outlet Size`,
    CAST(SUM(`Total Sales`) AS DECIMAL(10,2)) AS Total_Sales,
    CAST(
        SUM(`Total Sales`) * 100.0 / 
        SUM(SUM(`Total Sales`)) OVER () 
        AS DECIMAL(10,2)
    ) AS Sales_Percentage
FROM blinkit
GROUP BY `Outlet Size`
ORDER BY Total_Sales DESC;


-- query to find the total sales, sales percentage, average sales, number of items, and average rating for each Outlet Location Type

SELECT 
    `Outlet Location Type`,
    CAST(SUM(`Total Sales`) AS DECIMAL(10,2)) AS Total_Sales,
    CAST(
        SUM(`Total Sales`) * 100.0 / 
        SUM(SUM(`Total Sales`)) OVER () 
        AS DECIMAL(10,2)
    ) AS Sales_Percentage,
    CAST(AVG(`Total Sales`) AS DECIMAL(10,1)) AS Avg_Sales,
    COUNT(*) AS No_Of_Items,
    CAST(AVG(`Rating`) AS DECIMAL(10,2)) AS Avg_Rating
FROM blinkit
GROUP BY `Outlet Location Type`
ORDER BY Total_Sales DESC;


select * from blinkit;


--      end


